%.class: %.java
	javac $<

CLASSES = \
	MainFrame.java \
	MainMainInterface.java \
	PNGGUI.java \
	ColumnEdge.java \
	TableGUI.java \
	TableEdge.java \
	Test.java

classes: $(CLASSES:.java=.class)

clean:
	rm *.class